# Config file for automatic testing at travis-ci.org

language: python

sudo: false

python:
  - 3.7
  - 3.6
  - 3.5

env:
  matrix:
  - DJANGO='django30'
  - DJANGO='django22'
  - TOXENV='pep8'
  - TOXENV='isort'
  - TOXENV='docs'

services:
  - redis-server

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then export PYVER=py35; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then export PYVER=py36; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then export PYVER=py37; fi"
  - "if [[ ${DJANGO}z != 'z' ]]; then export TOXENV=$PYVER-$DJANGO; fi"

# command to run tests, e.g. python setup.py test
script: COMMAND='coverage run' tox -e$TOXENV

before_install:
  - pip install -U tox>=1.8 coveralls codecov wheel pip
after_success:
  - codecov
  - coveralls

matrix:
  exclude:
  - python: 3.5
    env: TOXENV='pep8'
  - python: 3.5
    env: TOXENV='isort'
  - python: 3.5
    env: TOXENV='docs'
  - python: 3.5
    env: DJANGO='django30'
  - python: 3.6
    env: TOXENV='pep8'
  - python: 3.6
    env: TOXENV='isort'
  - python: 3.6
    env: TOXENV='docs'

cache:
   directories:
     - $HOME/.pip-accel
     - $HOME/.cache/pip


