# Generated by Django 1.9.4 on 2016-04-04 19:56

import django.db.models.deletion
import django.utils.timezone
import meta.models
from django.conf import settings
from django.db import migrations, models

import knocker.mixins


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MultiLanguagePost",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "multilanguage blog article",
                "verbose_name_plural": "multilanguage blog articles",
            },
            bases=(knocker.mixins.KnockerModel, meta.models.ModelMeta, models.Model),
        ),
        migrations.CreateModel(
            name="MultiLanguagePostTranslation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(db_index=True, max_length=15, verbose_name="Language"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("slug", models.SlugField(blank=True, verbose_name="slug")),
                (
                    "master",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="example_app.MultiLanguagePost",
                    ),
                ),
            ],
            options={
                "managed": True,
                "db_table": "example_app_multilanguagepost_translation",
                "db_tablespace": "",
                "default_permissions": (),
                "verbose_name": "multilanguage blog article Translation",
            },
        ),
        migrations.CreateModel(
            name="NoKnockPost",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("slug", models.SlugField(blank=True, verbose_name="slug")),
            ],
            options={
                "verbose_name": "no knocj blog article",
                "verbose_name_plural": "no knocj blog articles",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("slug", models.SlugField(verbose_name="slug")),
                ("abstract", models.TextField(verbose_name="Abstract")),
                (
                    "meta_description",
                    models.TextField(blank=True, default="", verbose_name="Post meta description"),
                ),
                (
                    "meta_keywords",
                    models.TextField(blank=True, default="", verbose_name="Post meta keywords"),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "date_published",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Published Since",
                    ),
                ),
                (
                    "date_published_end",
                    models.DateTimeField(blank=True, null=True, verbose_name="Published Until"),
                ),
                (
                    "main_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images",
                        verbose_name="Main image",
                    ),
                ),
                (
                    "text",
                    models.TextField(blank=True, default="", verbose_name="Post text"),
                ),
                ("image_url", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
            ],
            options={
                "ordering": ("-date_published", "-date_created"),
                "get_latest_by": "date_published",
                "verbose_name": "blog article",
                "verbose_name_plural": "blog articles",
            },
            bases=(knocker.mixins.KnockerModel, meta.models.ModelMeta, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name="multilanguageposttranslation",
            unique_together={("language_code", "master")},
        ),
    ]
