# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-20 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noknockpost',
            options={'verbose_name': 'no knock blog article', 'verbose_name_plural': 'no knock blog articles'},
        ),
    ]
